service:
  name: bottle-smartad-serverless-ts

custom: ${file(ymls/custom.yml)}

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function
  - serverless-create-global-dynamodb-table
  - serverless-plugin-include-dependencies

package:
  individually: true
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
    - node_modules/**/aws-sdk/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
    name: bottle-smartad-serverless-${self:provider.stage}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    DEBUG: "*"
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
    - Effect: Allow
      Action: lambda:InvokeFunction
      Resource: arn:aws:lambda:us-east-1:*:function:${self:service}-dev-hello

functions:
  - ${file(src/functions/base/index.yml)}
  - ${file(src/functions/simpleResponse/index.yml)}
